version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    hostname: "sql01"
    command: /bin/bash ./docker/entrypoint.sh
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./docker/:/docker/
 
  pokeoneweb.webapi:
    image: ${DOCKER_REGISTRY-}pokeonewebwebapi
    build:
      context: .
      dockerfile: PokeOneWeb/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - DB_HOST=db
    depends_on:
      - db
  
volumes:
  dbdata:
