// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeOneWeb.Data;

namespace PokeOneWeb.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201020111547_temp_learnablemoves")]
    partial class temp_learnablemoves
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EffectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.BagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BagCategory");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.CurrencyAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("LearnableMoveLearnMethodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("LearnableMoveLearnMethodId");

                    b.ToTable("CurrencyAmount");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ElementalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ElementalType");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ElementalTypeCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PrimaryTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTypeId");

                    b.HasIndex("SecondaryTypeId");

                    b.ToTable("ElementalTypeCombination");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ElementalTypeRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AttackEffectivity")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("AttackingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DefendingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackingTypeId");

                    b.HasIndex("DefendingTypeId");

                    b.ToTable("ElementalTypeRelation");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventRegionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventRegionId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("BasePokemonVarietyId")
                        .HasColumnType("int");

                    b.Property<int>("EvolutionChainId")
                        .HasColumnType("int");

                    b.Property<string>("EvolutionTrigger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvolvedPokemonVarietyId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasePokemonVarietyId");

                    b.HasIndex("EvolutionChainId");

                    b.HasIndex("EvolvedPokemonVarietyId");

                    b.ToTable("Evolution");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.EvolutionChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PokeApiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EvolutionChain");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BagCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BagCategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LearnableMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MoveId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonVarietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoveId");

                    b.HasIndex("PokemonVarietyId");

                    b.ToTable("LearnableMove");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LearnableMoveApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gen7LearnMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Generations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LevelLearnedAt")
                        .HasColumnType("int");

                    b.Property<string>("MoveName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonVarietyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LearnableMoveApis");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LearnableMoveLearnMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LearnableMoveId")
                        .HasColumnType("int");

                    b.Property<int>("MoveLearnMethodId")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnableMoveId");

                    b.HasIndex("MoveLearnMethodId");

                    b.HasIndex("RequiredItemId");

                    b.ToTable("LearnableMoveLearnMethod");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("bit");

                    b.Property<int>("LocationGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Location");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LocationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("LocationGroup");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int>("DamageClassId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoInclude")
                        .HasColumnType("bit");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ElementalTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DamageClassId");

                    b.HasIndex("ElementalTypeId");

                    b.ToTable("Move");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.MoveDamageClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MoveDamageClass");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.MoveLearnMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MoveLearnMethod");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.MoveLearnMethodLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MoveLearnMethodId")
                        .HasColumnType("int");

                    b.Property<string>("PlacementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MoveLearnMethodId");

                    b.ToTable("MoveLearnMethodLocation");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PlacedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlacementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("PlacedItem");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PokemonAvailability");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonVarietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PokemonVarietyId");

                    b.ToTable("PokemonForm");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonHeldItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonVarietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PokemonVarietyId");

                    b.ToTable("PokemonHeldItem");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DefaultVarietyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultVarietyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PokedexNumber")
                        .IsUnique();

                    b.ToTable("PokemonSpecies");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonVariety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BaseStatsId")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultFormId")
                        .HasColumnType("int");

                    b.Property<bool>("DoInclude")
                        .HasColumnType("bit");

                    b.Property<int?>("ElementalTypeCombinationId")
                        .HasColumnType("int");

                    b.Property<int?>("EvYieldId")
                        .HasColumnType("int");

                    b.Property<int>("EvolutionChainId")
                        .HasColumnType("int");

                    b.Property<int?>("HiddenAbilityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PokeApiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryAbilityId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryAbilityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseStatsId");

                    b.HasIndex("DefaultFormId");

                    b.HasIndex("ElementalTypeCombinationId");

                    b.HasIndex("EvYieldId");

                    b.HasIndex("EvolutionChainId");

                    b.HasIndex("HiddenAbilityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PokemonSpeciesId");

                    b.HasIndex("PrimaryAbilityId");

                    b.HasIndex("SecondaryAbilityId");

                    b.ToTable("PokemonVariety");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MoneyReward")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("QuestTypeId");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.QuestItemReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuestId");

                    b.ToTable("QuestItemReward");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.QuestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestType");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEventRegion")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Region");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Season");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.SeasonTimeOfDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimeOfDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TimeOfDayId");

                    b.ToTable("SeasonTimeOfDay");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ShopBoughtItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PriceId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopBoughtItem");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ShopSoldItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PriceId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopSoldItem");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Spawn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonFormId")
                        .HasColumnType("int");

                    b.Property<int>("SpawnTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PokemonFormId");

                    b.HasIndex("SpawnTypeId");

                    b.ToTable("Spawn");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.SpawnOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EncounterCount")
                        .HasColumnType("int");

                    b.Property<int>("PokemonSpawnId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("SpawnCommonality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpawnProbability")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TimeOfDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonSpawnId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TimeOfDayId");

                    b.ToTable("SpawnOpportunity");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.SpawnType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SpawnType");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.TimeOfDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("TimeOfDay");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Currency", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.CurrencyAmount", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.LearnableMoveLearnMethod", null)
                        .WithMany("Price")
                        .HasForeignKey("LearnableMoveLearnMethodId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ElementalTypeCombination", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.ElementalType", "PrimaryType")
                        .WithMany("ElementalTypeCombinationsAsPrimaryType")
                        .HasForeignKey("PrimaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.ElementalType", "SecondaryType")
                        .WithMany("ElementalTypeCombinationsAsSecondaryType")
                        .HasForeignKey("SecondaryTypeId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ElementalTypeRelation", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.ElementalType", "AttackingType")
                        .WithMany("AttackingDamageRelations")
                        .HasForeignKey("AttackingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.ElementalType", "DefendingType")
                        .WithMany("DefendingDamageRelations")
                        .HasForeignKey("DefendingTypeId")
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Event", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Region", "EventRegion")
                        .WithMany()
                        .HasForeignKey("EventRegionId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Evolution", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "BasePokemonVariety")
                        .WithMany()
                        .HasForeignKey("BasePokemonVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.EvolutionChain", "EvolutionChain")
                        .WithMany("Evolutions")
                        .HasForeignKey("EvolutionChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "EvolvedPokemonVariety")
                        .WithMany()
                        .HasForeignKey("EvolvedPokemonVarietyId")
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Item", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.BagCategory", "BagCategory")
                        .WithMany("Items")
                        .HasForeignKey("BagCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LearnableMove", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "PokemonVariety")
                        .WithMany("LearnableMoves")
                        .HasForeignKey("PokemonVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LearnableMoveLearnMethod", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.LearnableMove", "LearnableMove")
                        .WithMany("LearnMethods")
                        .HasForeignKey("LearnableMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.MoveLearnMethod", "MoveLearnMethod")
                        .WithMany()
                        .HasForeignKey("MoveLearnMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Item", "RequiredItem")
                        .WithMany()
                        .HasForeignKey("RequiredItemId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Location", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.LocationGroup", "LocationGroup")
                        .WithMany("Locations")
                        .HasForeignKey("LocationGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.LocationGroup", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Region", "Region")
                        .WithMany("LocationGroups")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Move", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.MoveDamageClass", "DamageClass")
                        .WithMany()
                        .HasForeignKey("DamageClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.ElementalType", "ElementalType")
                        .WithMany("Moves")
                        .HasForeignKey("ElementalTypeId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.MoveLearnMethodLocation", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.MoveLearnMethod", "MoveLearnMethod")
                        .WithMany("Locations")
                        .HasForeignKey("MoveLearnMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PlacedItem", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany("PlacedItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Location", "Location")
                        .WithMany("PlacedItems")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonForm", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.PokemonAvailability", "Availability")
                        .WithMany()
                        .HasForeignKey("AvailabilityId");

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "PokemonVariety")
                        .WithMany("Forms")
                        .HasForeignKey("PokemonVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonHeldItem", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany("HeldItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "PokemonVariety")
                        .WithMany("HeldItems")
                        .HasForeignKey("PokemonVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonSpecies", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.PokemonVariety", "DefaultVariety")
                        .WithMany()
                        .HasForeignKey("DefaultVarietyId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.PokemonVariety", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Stats", "BaseStats")
                        .WithMany()
                        .HasForeignKey("BaseStatsId");

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonForm", "DefaultForm")
                        .WithMany()
                        .HasForeignKey("DefaultFormId");

                    b.HasOne("PokeOneWeb.Data.Entities.ElementalTypeCombination", "ElementalTypeCombination")
                        .WithMany("PokemonVarieties")
                        .HasForeignKey("ElementalTypeCombinationId");

                    b.HasOne("PokeOneWeb.Data.Entities.Stats", "EvYield")
                        .WithMany()
                        .HasForeignKey("EvYieldId");

                    b.HasOne("PokeOneWeb.Data.Entities.EvolutionChain", "EvolutionChain")
                        .WithMany()
                        .HasForeignKey("EvolutionChainId")
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Ability", "HiddenAbility")
                        .WithMany("PokemonVarietiesAsHiddenAbility")
                        .HasForeignKey("HiddenAbilityId");

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonSpecies", "PokemonSpecies")
                        .WithMany("Varieties")
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Ability", "PrimaryAbility")
                        .WithMany("PokemonVarietiesAsPrimaryAbility")
                        .HasForeignKey("PrimaryAbilityId");

                    b.HasOne("PokeOneWeb.Data.Entities.Ability", "SecondaryAbility")
                        .WithMany("PokemonVarietiesAsSecondaryAbility")
                        .HasForeignKey("SecondaryAbilityId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Quest", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("PokeOneWeb.Data.Entities.QuestType", "QuestType")
                        .WithMany("Quests")
                        .HasForeignKey("QuestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.QuestItemReward", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany("QuestRewardItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Quest", "Quest")
                        .WithMany("ItemRewards")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.SeasonTimeOfDay", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId");

                    b.HasOne("PokeOneWeb.Data.Entities.TimeOfDay", "TimeOfDay")
                        .WithMany("SeasonTimes")
                        .HasForeignKey("TimeOfDayId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Shop", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ShopBoughtItem", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany("BoughtItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.CurrencyAmount", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Shop", "Shop")
                        .WithMany("BoughtItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.ShopSoldItem", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Item", "Item")
                        .WithMany("SoldItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.CurrencyAmount", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Shop", "Shop")
                        .WithMany("SoldItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.Spawn", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Location", "Location")
                        .WithMany("PokemonSpawns")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.PokemonForm", "PokemonForm")
                        .WithMany("PokemonSpawns")
                        .HasForeignKey("PokemonFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.SpawnType", "SpawnType")
                        .WithMany()
                        .HasForeignKey("SpawnTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeOneWeb.Data.Entities.SpawnOpportunity", b =>
                {
                    b.HasOne("PokeOneWeb.Data.Entities.Spawn", "PokemonSpawn")
                        .WithMany("SpawnOpportunities")
                        .HasForeignKey("PokemonSpawnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeOneWeb.Data.Entities.TimeOfDay", "TimeOfDay")
                        .WithMany()
                        .HasForeignKey("TimeOfDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
