// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeOneWeb.Data;

namespace PokeOneWeb.Data.ReadModelDbMigrations
{
    [DbContext(typeof(ReadModelDbContext))]
    partial class ReadModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.AttackEffectivityReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BuildReadModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Effectivity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildReadModelId");

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("AttackEffectivityReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.BuildReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbilityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("AtkEv")
                        .HasColumnType("int");

                    b.Property<string>("BuildDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefEv")
                        .HasColumnType("int");

                    b.Property<int>("HpEv")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.Property<int>("SpaEv")
                        .HasColumnType("int");

                    b.Property<int>("SpdEv")
                        .HasColumnType("int");

                    b.Property<int>("SpeEv")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("BuildReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.EntityTypeReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceName")
                        .IsUnique()
                        .HasFilter("[ResourceName] IS NOT NULL");

                    b.ToTable("EntityTypeReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.EvolutionAbilityReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbilityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonSortIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonVarietyAsHiddenAbilityId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonVarietyAsPrimaryAbilityId")
                        .HasColumnType("int");

                    b.Property<int?>("PokemonVarietyAsSecondaryAbilityId")
                        .HasColumnType("int");

                    b.Property<int>("RelativeStageIndex")
                        .HasColumnType("int");

                    b.Property<string>("SpriteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonVarietyAsHiddenAbilityId");

                    b.HasIndex("PokemonVarietyAsPrimaryAbilityId");

                    b.HasIndex("PokemonVarietyAsSecondaryAbilityId");

                    b.ToTable("EvolutionAbilityReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.EvolutionReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<string>("BaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasePrimaryElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseSecondaryElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseSortIndex")
                        .HasColumnType("int");

                    b.Property<string>("BaseSpriteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseStage")
                        .HasColumnType("int");

                    b.Property<string>("EvolutionTrigger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolvedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolvedPrimaryElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolvedResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvolvedSecondaryElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvolvedSortIndex")
                        .HasColumnType("int");

                    b.Property<string>("EvolvedSpriteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvolvedStage")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReversible")
                        .HasColumnType("bit");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId");

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("EvolutionReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.HuntingConfigurationReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<string>("Nature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId");

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("HuntingConfigurationReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.ItemOptionReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("BuildReadModelId");

                    b.ToTable("ItemOptionReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.ItemStatBoostPokemonReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<decimal>("AttackBoost")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("DefenseBoost")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("HasRequiredPokemon")
                        .HasColumnType("bit");

                    b.Property<decimal>("HitPointsBoost")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ItemEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredPokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredPokemonResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpecialAttackBoost")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("SpecialDefenseBoost")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("SpeedBoost")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.ToTable("ItemStatBoostPokemonReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.LearnMethodReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LearnMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LearnableMoveReadModelId")
                        .HasColumnType("int");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LearnableMoveReadModelId");

                    b.ToTable("LearnMethodReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.LearnableMoveReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<string>("DamageClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("MoveName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("LearnableMoveReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.MoveOptionReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<int?>("BuildReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("DamageClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("BuildReadModelId");

                    b.ToTable("MoveOptionReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.MoveReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("AttackPower")
                        .HasColumnType("int");

                    b.Property<string>("DamageClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.ToTable("MoveReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.NatureOptionReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("NatureEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NatureName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("BuildReadModelId");

                    b.ToTable("NatureOptionReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.NatureReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.ToTable("NatureReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("AttackEv")
                        .HasColumnType("int");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CatchRate")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("DefenseEv")
                        .HasColumnType("int");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("HiddenAbility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiddenAbilityEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<int>("HitPointsEv")
                        .HasColumnType("int");

                    b.Property<bool>("IsFullyEvolved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMega")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryAbility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryAbilityEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PvpTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PvpTierSortIndex")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecondaryAbility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryAbilityEffect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("int");

                    b.Property<int>("SpecialAttackEv")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("int");

                    b.Property<int>("SpecialDefenseEv")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("SpeedEv")
                        .HasColumnType("int");

                    b.Property<string>("SpriteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("ResourceName")
                        .IsUnique()
                        .HasFilter("[ResourceName] IS NOT NULL");

                    b.ToTable("PokemonVarietyReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.PokemonVarietyUrlReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("PokemonVarietyUrlReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SeasonReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<int?>("SpawnReadModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpawnReadModelId");

                    b.ToTable("SeasonReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SimpleLearnableMoveReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<string>("MoveResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonVarietyApplicationDbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationDbId")
                        .IsUnique();

                    b.ToTable("SimpleLearnableMoveReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SpawnReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationDbId")
                        .HasColumnType("int");

                    b.Property<string>("EventEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HighestLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsEvent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInfinite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSyncable")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationSortIndex")
                        .HasColumnType("int");

                    b.Property<int>("LowestLevel")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonFormSortIndex")
                        .HasColumnType("int");

                    b.Property<string>("PokemonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PokemonResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokemonVarietyReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("RarityString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RarityValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RegionColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpawnType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpawnTypeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpawnTypeSortIndex")
                        .HasColumnType("int");

                    b.Property<string>("SpriteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PokemonVarietyReadModelId");

                    b.ToTable("SpawnReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.TimeOfDayReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<int?>("SpawnReadModelId")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpawnReadModelId");

                    b.ToTable("TimeOfDayReadModel");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.AttackEffectivityReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.BuildReadModel", null)
                        .WithMany("OffensiveCoverage")
                        .HasForeignKey("BuildReadModelId");

                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("DefenseAttackEffectivities")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.BuildReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("Builds")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.EvolutionAbilityReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("HiddenEvolutionAbilities")
                        .HasForeignKey("PokemonVarietyAsHiddenAbilityId")
                        .OnDelete(DeleteBehavior.ClientNoAction);

                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("PrimaryEvolutionAbilities")
                        .HasForeignKey("PokemonVarietyAsPrimaryAbilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("SecondaryEvolutionAbilities")
                        .HasForeignKey("PokemonVarietyAsSecondaryAbilityId")
                        .OnDelete(DeleteBehavior.ClientNoAction);
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.EvolutionReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("Evolutions")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.HuntingConfigurationReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("HuntingConfigurations")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.ItemOptionReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.BuildReadModel", null)
                        .WithMany("ItemOptions")
                        .HasForeignKey("BuildReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.LearnMethodReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.LearnableMoveReadModel", null)
                        .WithMany("LearnMethods")
                        .HasForeignKey("LearnableMoveReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.LearnableMoveReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("LearnableMoves")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.MoveOptionReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.BuildReadModel", null)
                        .WithMany("MoveOptions")
                        .HasForeignKey("BuildReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.NatureOptionReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.BuildReadModel", null)
                        .WithMany("NatureOptions")
                        .HasForeignKey("BuildReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.PokemonVarietyUrlReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("Urls")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SeasonReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.SpawnReadModel", null)
                        .WithMany("Seasons")
                        .HasForeignKey("SpawnReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SpawnReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", null)
                        .WithMany("Spawns")
                        .HasForeignKey("PokemonVarietyReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.TimeOfDayReadModel", b =>
                {
                    b.HasOne("PokeOneWeb.Data.ReadModels.SpawnReadModel", null)
                        .WithMany("TimesOfDay")
                        .HasForeignKey("SpawnReadModelId");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.BuildReadModel", b =>
                {
                    b.Navigation("ItemOptions");

                    b.Navigation("MoveOptions");

                    b.Navigation("NatureOptions");

                    b.Navigation("OffensiveCoverage");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.LearnableMoveReadModel", b =>
                {
                    b.Navigation("LearnMethods");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.PokemonVarietyReadModel", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("DefenseAttackEffectivities");

                    b.Navigation("Evolutions");

                    b.Navigation("HiddenEvolutionAbilities");

                    b.Navigation("HuntingConfigurations");

                    b.Navigation("LearnableMoves");

                    b.Navigation("PrimaryEvolutionAbilities");

                    b.Navigation("SecondaryEvolutionAbilities");

                    b.Navigation("Spawns");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("PokeOneWeb.Data.ReadModels.SpawnReadModel", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("TimesOfDay");
                });
#pragma warning restore 612, 618
        }
    }
}
