export class EvolutionLink {
    x0: number = 0;
    y0: number = 0;
    x1: number = 0;
    y1: number = 0;
    x2: number = 0;
    y2: number = 0;
    x3: number = 0;
    y3: number = 0;
    textX: number = 0;
    textY: number = 0;
    textWidth: number = 0;
    textHeight: number = 0;
    unavailableX: number = 0;
    unavailableY: number = 0;
    baseResourceName: string = '';
    evolvedResourceName: string = '';
    evolutionTrigger: string = '';
    isReversible: boolean = false;
    isAvailable: boolean = false;
}