name: PokeOneWebApp
on: [push]
jobs:
  sonarcloud:
    name: SonarCloud-PokeOneWebApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: 3c910b639e6bff83c19d78f62688951784b83449
  #        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  build:
    name: Build-PokeOneWebApp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: PokeOneWeb/Frontend/pokeoneweb/package-lock.json
    - run: |
        npm ci
        npm run-script build
      working-directory: PokeOneWeb/Frontend/pokeoneweb

