name: PokeOneWebApp Pull Request
on:
  pull_request:
    branches:
      - master
      - development
jobs:
  build:
    name: Build-PokeOneWebApp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: PokeOneWeb/Frontend/pokeoneweb/package-lock.json
         
    - run: |
        npm ci
        npm run build -- --configuration production
      working-directory: PokeOneWeb/Frontend/pokeoneweb

    - name: Run Jasmine Unit-Tests
      run: npm test -- --browsers=ChromeHeadless
      working-directory: PokeOneWeb/Frontend/pokeoneweb

    - name: Run Cypress UI-Tests
      uses: cypress-io/github-action@v2
      with:
        working-directory: PokeOneWeb/Frontend/pokeoneweb
        wait-on: 'http://localhost:4200'
        wait-on-timeout: 120
        start: npm start
        browser: chrome

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with: 
        projectBaseDir: PokeOneWeb/Frontend/pokeoneweb
        args: >
          -Dsonar.organization=poke-one-web
          -Dsonar.projectKey=poke-one-web-frontend
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WEBAPP }}
