name: PokeOneApi
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build-PokeOneApi
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 6.0 channel

    - name: Begin Sonar Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:"poke-one-web-api" \
                                  /o:"poke-one-web" \
                                  /d:sonar.login="${{ secrets.SONAR_TOKEN_API }}" \
                                  /d:sonar.host.url="https://sonarcloud.io" \
                                  /d:sonar.cs.vstest.reportsPaths=TestResults/*.trx \
                                  /d:sonar.cs.opencover.reportsPaths=TestResults/*/coverage.opencover.xml

    - name: Build & Install dep.
      run: dotnet build PokeOneWeb.sln --configuration Release
    - name: Test
      run: dotnet test PokeOneWeb.sln --collect "XPlat Code Coverage" --results-directory TestResults/ --logger "trx;LogFileName=unittests.trx" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

    - name: End Sonar Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN_API }}"

    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'PokeOneWeb.DataSync/bin/Release/net6.0/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.POKEONEWEB_DATASYNC_CONNECTIONSTRING_DEV }}

    - uses: appleboy/ssh-action@master
      with:
        host: dev.pokeone.guide
        port: 22
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: sudo systemctl stop p1backend
    - uses: appleboy/scp-action@master
      with:
        host: dev.pokeone.guide
        port: 22
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        source: "PokeOneWeb/bin/Release/net6.0"
        target: "/opt/PokeOneWeb.Api"
        strip_components: 4
        overwrite: true
        - uses: appleboy/scp-action@master
      with:
        host: dev.pokeone.guide
        port: 22
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        source: "PokeOneWeb.DataSync/bin/Release/net6.0"
        target: "/opt/PokeOneWeb.DataSync"
        strip_components: 4
        overwrite: true
    - uses: appleboy/ssh-action@master
      with:
        host: dev.pokeone.guide
        port: 22
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: sudo systemctl start p1backend

