name: Release Frontend to Test
on:
  workflow_dispatch:

jobs:
  build:
    name: Build-PokeOneWebApp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - run: ls

      - run: |
          npm ci
          npm version $GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT.$(date +'%Y-%m-%d')
          npm run build -- --configuration test
        working-directory: Frontend/PokeOneWeb

      - uses: appleboy/scp-action@master
        with:
          host: test.pokeone.guide
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: "Frontend/PokeOneWeb/dist"
          target: "/opt/PokeOneWeb.WebApp/test"
          strip_components: 5
          overwrite: true
