name: PokeOneWebApp
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build-PokeOneWebApp
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: PokeOneWeb/Frontend/pokeoneweb/package-lock.json

    - run: |
        npm ci
        npm version ${env:BUILD_NUMBER}.0.$(date +'%Y-%m-%d')
        npm run build -- --configuration dev
      working-directory: PokeOneWeb/Frontend/pokeoneweb